import type { ScreenEntry } from './types';

/** Screens for P07 (owned by that page's folder; keep in sync with its `s=` states). */
export const screens: ScreenEntry[] = [
  {
    id: '7A',
    page: 7,
    title: 'Add event — manual entry',
    path: (ctx) => `/trip/${ctx.sampleTripId}/event/new`,
    auth: 'maya',
    notes: 'Other pages can prefill When with ?day=YYYY-MM-DD&start=HH:MM and send you back with ?return=<path>.',
  },
  {
    id: '7B',
    page: 7,
    title: 'Crowd estimate for the chosen place and time',
    path: (ctx) => `/trip/${ctx.sampleTripId}/event/new?s=busy`,
    auth: 'maya',
    notes: 'Jerónimos Monastery, Day 2 at 12 PM: “Usually busy”, with a calmer-time tip. Estimates are illustrative.',
  },
  {
    id: '7C',
    page: 7,
    title: 'Time conflict warning',
    path: (ctx) => `/trip/${ctx.sampleTripId}/event/new?s=conflict`,
    auth: 'maya',
    notes: 'LX Factory, Day 2, 3:45–5:00 PM overlaps Santa Justa Lift; the button reads “Save anyway”.',
  },
  { id: '7D', page: 7, title: 'Upload a confirmation screenshot', path: (ctx) => `/trip/${ctx.sampleTripId}/event/new?tab=upload`, auth: 'maya' },
  {
    id: '7E',
    page: 7,
    title: 'Reading the screenshot…',
    path: (ctx) => `/trip/${ctx.sampleTripId}/event/new?tab=upload&s=reading`,
    auth: 'maya',
    notes: 'Simulated; held on the middle step.',
  },
  {
    id: '7F',
    page: 7,
    title: 'Review extracted details, fill the gaps',
    path: (ctx) => `/trip/${ctx.sampleTripId}/event/new?tab=upload&s=review`,
    auth: 'maya',
    notes: 'Sample confirmation from a fictional vendor (TicketLine): National Tile Museum, Day 4 at 2:30 PM. End time and who’s coming need input.',
  },
  {
    id: '7G',
    page: 7,
    title: 'Unreadable image',
    path: (ctx) => `/trip/${ctx.sampleTripId}/event/new?tab=upload&s=unreadable`,
    auth: 'maya',
    notes: 'Naturally: upload a tiny image (under 300 px) or one the browser can’t open.',
  },
  {
    id: '7H',
    page: 7,
    title: 'Edit an event',
    path: (ctx) => `/trip/${ctx.sampleTripId}/event/${ctx.sampleTripId}-e4`,
    auth: 'maya',
    notes: 'Delete asks first, then offers Undo.',
  },
  { id: '7I', page: 7, title: 'View-only event (Viewer)', path: (ctx) => `/trip/${ctx.sampleTripId}/event/${ctx.sampleTripId}-e4`, auth: 'maya', as: 'viewer' },
  {
    id: '7J',
    page: 7,
    title: 'Day editor: only assigned days',
    path: (ctx) => `/trip/${ctx.sampleTripId}/event/new`,
    auth: 'maya',
    as: 'day',
    notes: 'Sam can only pick Day 3; his events on other days open read-only.',
  },
];
