import type { ScreenEntry } from './types';

/** Screens for P13 (owned by that page's folder; keep in sync with its `s=` states). */
export const screens: ScreenEntry[] = [
  {
    id: '13A',
    page: 13,
    title: 'Food & dining tiles',
    path: (ctx) => `/trip/${ctx.sampleTripId}/people`,
    auth: 'maya',
    notes: 'Combined from accepted members’ surveys: diet/allergies, local vs. home, spend (+ planned-meal check), simple vs. extravagant, atmosphere.',
  },
  {
    id: '13B',
    page: 13,
    title: 'Travel preferences & limitations tiles',
    path: (ctx) => `/trip/${ctx.sampleTripId}/people?section=travel`,
    auth: 'maya',
    notes: 'Accessibility with an itinerary check, walking limits, other needs, tickets still to book, interests (historic vs. modern vs. cultural).',
  },
  {
    id: '13C',
    page: 13,
    title: 'Collaborators (Owner can manage)',
    path: (ctx) => `/trip/${ctx.sampleTripId}/people?section=collaborators`,
    auth: 'maya',
    notes: 'Desktop: sticky rail. Phone: “People” section. Role badges open the role sheet; Remove / Cancel invite per row.',
  },
  {
    id: '13D',
    page: 13,
    title: 'Change role / assign days',
    path: (ctx) => `/trip/${ctx.sampleTripId}/people?s=role`,
    auth: 'maya',
    overlay: true,
    notes: 'Opens for Sam (Day editor, Day 3). Day editor needs at least one day.',
  },
  {
    id: '13E',
    page: 13,
    title: 'Invite a collaborator',
    path: (ctx) => `/trip/${ctx.sampleTripId}/people?s=invite`,
    auth: 'maya',
    overlay: true,
    notes: 'Name + email; joins as a pending Viewer. Simulated: nothing is sent.',
  },
  {
    id: '13F',
    page: 13,
    title: 'Remove a collaborator',
    path: (ctx) => `/trip/${ctx.sampleTripId}/people?s=remove`,
    auth: 'maya',
    overlay: true,
    notes: 'Opens for Priya. The toast after removing has Undo.',
  },
  {
    id: '13G',
    page: 13,
    title: 'Non-owner: roles read-only',
    path: (ctx) => `/trip/${ctx.sampleTripId}/people`,
    auth: 'maya',
    as: 'viewer',
    notes: 'Viewing as Priya: lock note, locked Invite, no role or remove controls. Tiles stay visible to everyone.',
  },
  {
    id: '13H',
    page: 13,
    title: 'Response count + pending invitee',
    path: '/people',
    auth: 'new',
    notes: 'Fresh account: “4 of 5 travelers shared preferences · Diego Alvarez hasn’t accepted the invite yet” plus an “Add your preferences” nudge.',
  },
];
